import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class UserProfile {

	// id cannot be less than zero; 
	// zero case is only when a new user profile is being created; 
	// 	- an actual id will be generated by another sub-system (example database auto-increment primary key)
	// NOTE: this comment is an example on how you should describe your use of validation annotations in this class (Task 4b. requirement)
	@Min(value = 0) 
	private int id;

	// TODO 34: add which annotation? Does it have any params?
	//	- why are you adding this annotation?
	private String userName;

	// TODO 35: add which annotation? Does it have any params?
	//	- why are you adding this annotation?	
	private String firstName;

	// TODO 35: add which annotation? Does it have any params?
	//	- why are you adding this annotation?	
	private String lastName;

	// TODO 36: add which annotation? Does it have any params?
	//	- why are you adding this annotation?
	private String otherNames;

	// TODO 37: add which annotation? Does it have any params?
	//	- why are you adding this annotation?
	private LocalDate dateOfBirth;

	// TODO 38: Email annotation here - Does your design have any params?
	private String email;

	public UserProfile(int id, String userName, String firstName, String lastName, String otherNames, LocalDate dateOfBirth, String email) {
		this.id = id;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.otherNames = otherNames;
		this.dateOfBirth = dateOfBirth;
		this.email = email;
	}


	public int getId() {
		return this.id;
	}

	public String getUserName() {
		return this.userName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public String getOtherNames() {
		return this.otherNames;
	}		

	public LocalDate getDateOfBirth() {
		return this.dateOfBirth;
	}

	public String toString() {
		DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");

		return "\nUserProfile [\n\tid: " + this.id
			+ "\n\tuser name: " + this.userName
			+ "\n\tfirst name: " + this.firstName
			+ "\n\tlast name: " + this.lastName
			+ (this.otherNames != null && this.otherNames.trim().length() > 0 ? "\n\tother names: " + this.otherNames : "")
			+ "\n\tdate of birth: " + this.dateOfBirth.format(dtf) 
			+ "\n\temail: " + this.email
			+ "\n]";
	}

	// To perform some quick tests
	public static void main(String [] args) {
		// TODO 39: CSE4OAD
		// create a 2 instances of VALID UserProfile
		// create a 2 instances of INVALID UserProfile
		// Use Validator.validate(...) to validate each of the 4 instances

	}
}